### ISSUE TITLE
Fix System Object Showing Extra GUI and Drop Down

### ISSUE THREAD

**Issue by JasonJonesLASM** [LifeandStyleMedia/UAlive#54]

**Comment by jrDev1** [comment]
![image](https://user-images.githubusercontent.com/16272193/93156733-b77bce80-f6d6-11ea-84ec-dc6eec84b278.png)

**Comment by JasonJonesLASM** [comment]
Fixed!

**Comment by jrDev1** [comment]
![image](https://user-images.githubusercontent.com/16272193/93382064-911d7680-f82f-11ea-9605-504c0accedfb.png)

Not sure if related. Also clicking on that variable in image gives this error:
NullReferenceException
UnityEngine.Object.get_name () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:189)
Lasm.UAlive.UAClassInspector.GetHeight (System.Single width, UnityEngine.GUIContent label) (at Assets/LifeandStyleMedia/UAlive/Core/Editor/Units/UAlive/Widgets/UAClassInspector.cs:74)
Ludiq.Inspector.GetCachedHeight (System.Single width, UnityEngine.GUIContent label, Ludiq.Inspector parentInspector) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Inspection/Inspector.cs:192)
UnityEngine.Debug:LogException(Exception)
Ludiq.Inspector:Draw(Rect, GUIContent) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Inspection/Inspector.cs:153)
Ludiq.LudiqGUI:Inspector(Metadata, Rect, GUIContent) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Interface/LudiqGUI.cs:86)
Ludiq.ReflectedInspector:OnMemberGUI(Metadata, Rect) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Inspection/Special/ReflectedInspector.cs:113)
Ludiq.ReflectedInspector:OnGUI(Rect, GUIContent) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Inspection/Special/ReflectedInspector.cs:98)
Ludiq.Inspector:Draw(Rect, GUIContent) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Inspection/Inspector.cs:104)
Ludiq.LudiqGUI:Inspector(Metadata, Rect, GUIContent) (at C:/Users/RohitMoni/Documents/Repos/bolt/Package/Ludiq.Core/Editor/Interface/LudiqGUI.cs:86)
Lasm.UAlive.UAClassPropertyDrawer:OnGUI(Rect, SerializedProperty, GUIContent) (at Assets/LifeandStyleMedia/UAlive/Core/Editor/Units/UAlive/Widgets/UAClassPropertyDrawer.cs:71)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

Thanks,
jrDev
