### ISSUE TITLE
Instance Object Values Don't Allow Scene References

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#60]
![image](https://user-images.githubusercontent.com/16272193/93496168-e6639180-f8dc-11ea-9f78-2ff0fe672111.png)
Thanks,
jrDev

**Comment by jrDev1** [comment]
Also not draggable:
![UAlive Gameobject Drag Issue](https://user-images.githubusercontent.com/16272193/93617954-a4058780-f9a4-11ea-8f01-dd99c796a16b.gif)

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Fixed

**Comment by jrDev1** [comment]
Should reopen to fix Generics too!

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Closed and opened a new issue for this specifiic https://github.com/LifeandStyleMedia/UAlive/issues/66:
