### ISSUE TITLE
Inspector Object reference variables set in edit mode are reset when game goes into play mode

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#61]
Whenever I add a reference to an object in edit mode in the inspector, it resets in play mode.

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Fixed

**Comment by jrDev1** [comment]
Reopen because Lists get reset still.

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Closing this and opened a new issue for this specific case: https://github.com/LifeandStyleMedia/UAlive/issues/65
