### ISSUE TITLE
Method Breadcrumbs

### ISSUE THREAD

**Issue by thezoob** [LifeandStyleMedia/UAlive#62]
![MethodBreadcrumbs](https://i.imgur.com/lIoFA7b.png)

Breadcrumbs that show which Class the Method's graph belongs to.

**Comment by JasonJonesLASM** [comment]
Complete!

![Breadcrumbs UAlive 1](https://lifeandstylemedia.com/images/github/breadcrumbs.png)

**Comment by jrDev1** [comment]
Can we get this clickable to go back to original class? Should I add a new issue for it?

**Comment by JasonJonesLASM** [comment]
Already posted that, you can see it here: https://github.com/LifeandStyleMedia/UAlive/issues/64
