### ISSUE TITLE
Reroute Unit continues connection

### ISSUE THREAD

**Issue by thezoob** [LifeandStyleMedia/UAlive#73]
![Reroute Unit](https://i.imgur.com/2wvChu0.gif)

Seems to only happen when it's between 2 Reroute units and when trying to replace an existing connection.

**Comment by JasonJonesLASM** [comment]
Closing this. I will be rewriting the behavior from scratch to work with all units, sometime this week, and a lot of the checks for specific types of units were part of the issue, amongst other things.
