### ISSUE TITLE
System.Object Class Unit height issue

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#80]
![image](https://user-images.githubusercontent.com/16272193/94460790-3ff27880-0187-11eb-9357-72ad89e6ca36.png)

**Comment by jrDev1** [comment]
Update: This auto fixes when you deselect and reselect. But still should be fixed for initial creation. Probably needs to be force updated.

**Comment by JasonJonesLASM** [comment]
Perfect. I actually got that figured out for the icons, so easy enough I assume.

**Comment by JasonJonesLASM** [comment]
I think I fixed this. If it's not on your end I can't reproduce. For me I add a Literal of my type that's a system.object. it takes a frame but then updates the height immediately after. Nothing I need to do.

Is that when it occurs? Perhaps your adding new variables while looking at the graph? That could be something that I didn't look out for.

Let me know if I should reopen this, if you have any more details as well. Thanks!
